services:
  db:
    image: postgres:14-alpine
    container_name: minisocial_db
    env_file:
      - .env
    environment:
      POSTGRES_DB: minisocialnetwork
      POSTGRES_USER: root
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
    - backend-nestjs_minisocial_pgdata:/var/lib/postgresql/data

  backend:
    build: .
    env_file:
      - .env
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: minisocialnetwork
    depends_on:
      - db
    ports:
      - "8081:8081"
volumes:
  backend-nestjs_minisocial_pgdata: